run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gosec:
    excludes:
      - G104 # Audit errors not checked (we handle this explicitly)
      - G101 # Hardcoded credentials (false positives on constant names)
      - G115 # Integer overflow (we control the input values)
    config:
      G306: "0644" # Expected file permissions

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (net.Conn).SetDeadline
      - (net.Conn).SetReadDeadline
      - (net.Conn).SetWriteDeadline

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude known issues in generated code
    - path: pkg/types/
      linters:
        - revive

  max-issues-per-linter: 50
  max-same-issues: 10
